name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Set Version
        run: npm --no-git-tag-version version prerelease --preid=$GITHUB_RUN_NUMBER
        if: ${{ !endsWith(github.ref, '/develop') }}
      - name: Build
        run: |
          npm --prefix api install
          npm --prefix api run build
          npm i vsce -g
          npm install
          cd ui && npm install
          cd ..
          vsce package
          mkdir dist
          cp *.vsix dist
          cd api
          npm pack
      - name: Upload Dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**
      - name: Upload API
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: api/dist/**
